version: "3.8"

services:
  mariadb:
    image: mariadb
    container_name: foostestbot-mariadb
    volumes:
      - ./initdb.d/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=FoosTestBot
      - TZ=${TZ}
  redis:
    image: redis
    container_name: foostestbot-redis
    command: "redis-server /usr/local/etc/redis/redis.conf"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  foostestbot:
    build: foos_test_bot/.
    image: nkuznetsov44/foostestbot:${DOCKER_TAG}
    container_name: foostestbot
    depends_on:
      - mariadb
      - redis
    ports:
      - ${WEBAPP_PORT}:8000
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=mariadb
      - MYSQL_DATABASE=FoosTestBot
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - WEBHOOK_HOST=${WEBHOOK_HOST}
      - WEBHOOK_PATH=${WEBHOOK_PATH}
      - WEBAPP_HOST=${WEBAPP_HOST}
      - WEBAPP_PORT=${WEBAPP_PORT}
      - TZ=${TZ}
      - LOG_LEVEL=${LOG_LEVEL}
  phpmyadmin:
    image: phpmyadmin
    container_name: foostestbot-phpmyadmin
    ports:
      - ${PMA_PORT}:80
    environment:
      - PMA_HOST=mariadb
  foostest-results-app:
    build: results_app/.
    image: nkuznetsov44/foostest-results-app:${DOCKER_TAG}
    container_name: foostest-results-app
    depends_on:
      - mariadb
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=mariadb
      - MYSQL_DATABASE=FoosTestBot
      - TZ=${TZ}
      - LOG_LEVEL=${LOG_LEVEL}
  foostest-results-app-nginx:
    image: nginx:latest
    container_name: foostest-results-app-nginx
    ports:
      - ${RESULTS_APP_PORT}:80
    volumes:
      - ./nginx-conf.d:/etc/nginx/conf.d
      - ./results_app/html:/var/www/foostest-results-app
      - ./results_app/js:/var/www/foostest-results-app/js
      - ./results_app/css:/var/www/foostest-results-app/css