version: "3.8"

services:
  mariadb:
    image: mariadb
    container_name: foostestbot-mariadb
    volumes:
      - ./initdb.d/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=FoosTestBot
      - TZ=${TZ}
  redis:
    image: redis
    container_name: foostestbot-redis
    command: "redis-server /usr/local/etc/redis/redis.conf"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  foostestbot:
    build:
      dockerfile: Dockerfile
      context: .
    image: nkuznetsov44/foostestbot:${DOCKER_TAG}
    container_name: foostestbot
    depends_on:
      - mariadb
      - redis
    ports:
      - ${WEBAPP_PORT}:8000
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=mariadb
      - MYSQL_DATABASE=FoosTestBot
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - WEBHOOK_HOST=${WEBHOOK_HOST}
      - WEBHOOK_PATH=${WEBHOOK_PATH}
      - WEBAPP_HOST=${WEBAPP_HOST}
      - WEBAPP_PORT=${WEBAPP_PORT}
      - TZ=${TZ}
      - LOG_LEVEL=${LOG_LEVEL}